# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  releaseBranchName: 'main'
  azureSubName: 'tbd'
  azureAppServiceDevName: 'aspen-app-service-dev'
  azureAppServiceTestName: 'aspen-app-service-test'

stages:
  - stage: 'Build'
    displayName: 'Bella the builder'
    jobs:
    - job: 'Build'
      displayName: 'Build and publish'
      pool:
        vmImage: 'ubuntu-20.04'
    variables:
      dotnetSdkVersion: '6.x'
      dotnetFramework: 'net6.0'
      targetRuntime: 'linux-64'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'
    - script: dotnet build --configuration $(BuildConfiguration)
      displayName: 'Build .NET $(dotnetSdkVersion) application'

    - task: DotNetCoreCli@2
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --framework $(dotnetFramework) --runtime $(targetRuntime) --self-contained --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'AspenWebApp'



